go-spatial/atlante

atlante/config/config.go, atlante/server/server.go, cmd/atlante/cmd/root.go, cmd/atlante/cmd/server.go, cmd/atlante/config/config.go, cmd/atlante/main.go, docker/Dockerfile-development
First part of #17  the info urls.
=> Issue 17 http server info

atlante/atlante.go, atlante/filestore/filestore.go, atlante/filestore/multi/multi.go, atlante/filestore/s3/README.md, atlante/filestore/s3/s3.go, atlante/server/server.go
Filestore can now return urls for paths.
=> [Feature] Added the ability for s3 to generate presigned urls

atlante/grids/cell.go, atlante/grids/grid5k/README.md, atlante/grids/grid5k/grid5k.go, atlante/grids/postgresql/README.md, atlante/grids/postgresql/postgresql.go, atlante/grids/register.go, atlante/server/server.go, cmd/atlante/config/config.go, cmd/atlante/grid_providers_reg.go
=> Added the 5k Grid provider.

atlante/grids/postgresql/README.md, atlante/server/README.md, atlante/server/server.go
Changed the info end point from lat/lng to lng/lat
=> [QuickFix] Change the latlng for url to lnglat

atlante/grids/grid5k/grid5k.go, atlante/server/server.go
=> [quickfix] added cors handling

atlante/grids/postgresql/README.md
Notes on how to setup and test PostGIS for use with `atlante`
=> Added PostGIS notes for `atlante`

atlante/atlante.go, atlante/notifiers/http/http.go, atlante/sheet.go, atlante/sheet_test.go
=> Fixed for mm conversion

atlante/atlante.go, atlante/server/coordinator/coordinator.go, atlante/server/coordinator/field/status.go, atlante/server/coordinator/logger/logger.go, atlante/server/coordinator/null/null.go, atlante/server/coordinator/postgresql/postgresql.go, atlante/server/server.go, atlante/sheet.go
Added URL end point to get all jobs, and their status in the sytem. The status of jobs returns the position and total number of possible states for the job.
=> Added ability to get all jobs.

atlante/server/coordinator/coordinator.go, atlante/server/coordinator/logger/logger.go, atlante/server/coordinator/null/null.go, atlante/server/coordinator/postgresql/README.md, atlante/server/coordinator/postgresql/postgresql.go, atlante/server/server.go
Updated main info api to include latest two jobs.
=> Updated main info api to include jobs

atlante/config/README.md, atlante/config/config_test.go, atlante/filestore/errors.go, atlante/filestore/filestore.go, atlante/filestore/s3/s3.go, atlante/grids/postgresql/README.md, atlante/grids/postgresql/postgresql.go, atlante/internal/urlutil/urlutil.go, atlante/notifiers/http/README.md, atlante/server/README.md, atlante/server/coordinator/coordinator_registerion_test.go, atlante/server/coordinator/postgresql/README.md, atlante/server/coordinator/postgresql/postgresql.go, atlante/server/server.go
Various fixes for documentation and documentation related issues.
fixes #52 
fixes #53 
fixes #54 
fixes #56 
fixes #57 
fixes #62 
fixes #65
=> Documention fixes

.travis.yml
The travis filter was based on the branch name, which for
pull requests into master, is master. I think what we want
instead is the head branch.
=> updated the travis filter

atlante/atlante.go, atlante/grids/postgresql/errors.go, atlante/grids/postgresql/postgresql.go, atlante/internal/urlutil/urlutil.go, atlante/server/coordinator/postgresql/postgresql.go, atlante/server/server.go, cmd/atlante/cmd/root.go
* #77 made the errors constants
* #78 Just use io.ReadCloser
* #79 Added comment to helper function
* #80 Moved hardcoded value to constant
* #81 Made sure Job is always an array in JSON output
=> [#77, #78, #79,#80,#81] fixed a few code aesthetic issues

atlante/server/server.go, go.sum
Added status handler for live checks.
Fixes #88
=> [88] added status handler

atlante/grids/cell.go, atlante/grids/postgresql/errors.go, atlante/grids/postgresql/postgresql.go, go.mod, go.sum, vendor/github.com/go-spatial/geom/bbox.go, vendor/github.com/go-spatial/geom/encoding/wkb/internal/consts/consts.go, vendor/github.com/go-spatial/geom/encoding/wkb/internal/decode/decode.go, vendor/github.com/go-spatial/geom/encoding/wkb/internal/encode/encode.go, vendor/github.com/go-spatial/geom/encoding/wkb/wkb.go, vendor/modules.txt
This allows the Postgres driver for grids to take optional fields.
fixes #82
=> Allow optional sql field

atlante/grids/postgresql/postgresql.go
=> Fixed rows not being closed and filling up connection pool

atlante/atlante.go, atlante/notifiers/http/http.go, atlante/notifiers/notifiers.go, atlante/notifiers/screen/README.md, atlante/notifiers/screen/screen.go, cmd/atlante/cmd/root.go, cmd/atlante/notifiers_reg.go, go.mod, go.sum, mbgl/image/image.go, vendor/github.com/gdey/cmd/.gitignore, vendor/github.com/gdey/cmd/LICENSE.md, vendor/github.com/gdey/cmd/README.md, vendor/github.com/gdey/cmd/main.go
This PR adds a `timeout` (in minutes) command line parameter to ensure that a job does not run for more than the time out.
The worker will respond to soft kills, enabling it to report back a failure for the job.
=> 87 mbgl timeout

atlante/atlante.go
Added checks for context cancelition in main PDF generation to notifiy when atlante is termindated.
=> [notifier] Added checks for context cancel in the main PDF generation

.vscode/settings.json, atlante/atlante.go, atlante/grids/cell.go, atlante/grids/grid5k/grid5k.go, atlante/grids/postgresql/postgresql.go, atlante/server/server.go, cmd/atlante/cmd/root.go
We now support arbitrary bounds.
#107
=> Support Bounds

atlante/atlante.go, atlante/filestore/file.go, atlante/grids/cell.go, atlante/image_structure.go, atlante/internal/resolution/resolution.go
You can now set the width and height of the image. This will cause everything to be recalcualted based on that width and height.
=> In the template you can now set the width and height of the image.

atlante/atlante.go, atlante/config/aws/aws.go, atlante/grids/cell.go, atlante/grids/grid5k/grid5k.go, atlante/grids/postgresql/postgresql.go, atlante/internal/env/dict.go, atlante/internal/resolution/resolution.go, atlante/job.pb.go, atlante/server/README.md, atlante/server/coordinator/coordinator.go, atlante/server/coordinator/logger/logger.go, atlante/server/coordinator/postgresql/postgresql.go, atlante/server/server.go, atlante/sheet.go, cmd/atlante/cmd/generate.go, cmd/atlante/cmd/root.go, cmd/atlante/grid_providers_reg.go, setqueue/setqueue.go, tools/tools.go
The pdf url will be fill out only after the job as compleated, and may take some time afterwards.
=> Added pdf urls to the status of a job.

atlante/grids/postgresql/README.md, atlante/server/README.md, atlante/server/server.go, atlante/sheet.go, atlante/style/style.go
Initial geojson grid api. For Atlante.
=> Initial GeoJSON grid api
